### ISSUE TITLE
Feature/Update/Request: Port to RIFT for 1.13.2+ support.

### ISSUE THREAD

**Issue by Xeddius** [1337Zero/Zombe#10]
Given that MCP will not be updated for quite some time (this is the largest minecraft code overhaul in minecraft's history.) and therefore Liteloader (dependent on mcp) will not be updated for a very long time, It may be a good idea to port over to the RIFT api, as it's up-to-date, clean, and supports 1.13.2

Rift can be found at: `https://minecraft.curseforge.com/projects/rift`

### Making mods work in many Minecraft versions

> With Rift, your mods will work throughout many Minecraft versions. Through optional mod compatibility modules, Rift will remap mods to updated obfuscated names and inject unimplemented vanilla methods back into classes, making the unstable Minecraft API stable. Although compatibility of all mods across many Minecraft versions may not be possible, most mods should work for at least a few versions.

**Comment by 1337Zero** [comment]
Im working at a rift port. But it will take some time till i fixed everything which is broken with 1.13.
And btw there is no 1.13.2 Rift yet :P 

Till yet i got FlyMod,SpeedMod,Infomod to work with Rift. Next will be Orehighlighter and Mobhighlighter

be prepared that the old configs may are broken completly.
Including keybindings, Block Ids and more stuff.

**Comment by 1337Zero** [comment]
https://github.com/1337Zero/Zombe/releases/tag/v0.0.6.0.0

here for u :)
