### ISSUE TITLE
(Request) Xray/Transparent Ground

### ISSUE THREAD

**Issue by Xeddius** [1337Zero/Zombe#7]
Please implement the xray feature of Zombe. Not the (ORE)xray feature! Specifically the mod that enables you to see through walls, it's extremely helpful when building and Minecraft hasn't been the same for me since losing this helpful tool.

**Comment by 1337Zero** [comment]
u mean this ?

![2017-12-03_23 54 59](https://user-images.githubusercontent.com/5228238/33530825-68fa00dc-d885-11e7-8769-efff414073af.png)

it is "cave-key" under orehighlighter

but since i need to override some internal classes for that, it can break with other mods

tested with 1.12.1 build

**Comment by Xeddius** [comment]
Thank you so much! I should have checked under that option! It didn't occur to me because I was used to Zombe having a dedicated menu for it.
